### ISSUE TITLE
undefined symbol: _ZN2at6detail20DynamicCUDAInterface10set_deviceE

### ISSUE THREAD

**Issue by woaiwoziji** [princeton-vl/CornerNet#50]
Hi everyone. What happened?
python test.py CornerNet --testiter 500000
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    from nnet.py_factory import NetworkFactory
  File "/home/jinxuany/CornerNet/nnet/py_factory.py", line 7, in <module>
    from models.py_utils.data_parallel import DataParallel
  File "/home/jinxuany/CornerNet/models/py_utils/__init__.py", line 6, in <module>
    from ._cpools import TopPool, BottomPool, LeftPool, RightPool
  File "/home/jinxuany/CornerNet/models/py_utils/_cpools/__init__.py", line 6, in <module>
    import top_pool, bottom_pool, left_pool, right_pool
ImportError: /home/jinxuany/.local/lib/python3.6/site-packages/cpools-0.0.0-py3.6-linux-x86_64.egg/top_pool.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at6detail20DynamicCUDAInterface10set_deviceE

**Comment by woaiwoziji** [comment]
cuda version was inconsistent with torch.version.cuda

**Comment by jmuyjl** [comment]
I have the same problem. How can I solve it?@woaiwoziji，If it's a CUDA problem, how do you solve it?

**Comment by MichaelCong** [comment]
I have the same problem. How can I solve it?
cuda version was consistent with torch.version.cuda
10.0.130

**Comment by YJLCV** [comment]
This problem was solved a long time ago. It seems to be a version problem. My version torch.version.cuda is 9.0.




------------------ 原始邮件 ------------------
发件人: "任聪"<notifications@github.com>;
发送时间: 2019年6月23日(星期天) 上午8:38
收件人: "princeton-vl/CornerNet"<CornerNet@noreply.github.com>;
抄送: "than."<1967547790@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [princeton-vl/CornerNet] undefined symbol:_ZN2at6detail20DynamicCUDAInterface10set_deviceE (#50)




I have the same problem. How can I solve it?
 cuda version was consistent with torch.version.cuda
 10.0.130

**Comment by lizhe960118** [comment]
@jmuyjl  my version is correct, but i still get this problem. why?

**Comment by lizhe960118** [comment]
1. First, check your cudnn version, cudnn must not be higher than the pytorch version. check you cuda version at the same time.
2. Second, use the gcc == 4.9 to compile your cpool code in ./models/py_utils/_cpool/ .
3. use the command
```
python setup.py install
```
instead of 
```
python setup.py install --user
```

**Comment by FHCGIT** [comment]
> I have the same problem. How can I solve it?
> cuda version was consistent with torch.version.cuda
> 10.0.130

Have you solve this problem? I meet it the same as you
